[package]
name = "commit"
version = "0.1.0"
edition = "2021"
description = "Command line tool to make convetions in git commit messages"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.2.1"
serde = { version = "1.0.130", features=["derive"] }
serde_json = "1.0.68"