name: Release

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Install cargo-generate-rpm
      run: cargo install cargo-generate-rpm
    - name: Install cargo-appimage
      run: cargo install cargo-appimage
    - name: Test
      run: cargo test --release
    - name: Build .deb
      run: cargo deb --verbose 
    - name: Upload .deb package
      run: |
        cp ./target/debian/*.deb ./commit_${GITHUB_REF##*/}_amd64.deb
        ./.github/workflows/upload_asset.sh \
          "alt-art/commit" ./commit_${GITHUB_REF##*/}_amd64.deb $GITHUB_TOKEN
    - name: Build .rpm
      run: cargo generate-rpm --verbose
    - name: Upload .rpm package
      run: |
        cp ./target/generate-rpm/rpm/*.rpm ./commit_${GITHUB_REF##*/}_x86_64.rpm
        ./.github/workflows/upload_asset.sh \
          "alt-art/commit" ./commit_${GITHUB_REF##*/}_x86_64.rpm $GITHUB_TOKEN
    - name: Build .AppImage
      run: cargo appimage --verbose
    - name: Upload .AppImage
      run: |
        cp ./*.AppImage ./commit_${GITHUB_REF##*/}_x86_64.AppImage
        ./.github/workflows/upload_asset.sh \
          "alt-art/commit" ./commit_${GITHUB_REF##*/}_x86_64.AppImage $GITHUB_TOKEN

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload portable executable
        run: |
          cp ./target/release/commit.exe ./commit-${GITHUB_REF##*/}-portable.exe
          ./.github/workflows/upload_asset.sh \
            "alt-art/commit" ./commit-${GITHUB_REF##*/}-portable.exe $GITHUB_TOKEN
